const DEFAULT_BORDER_COLOR = 'cyan'
const DEFAULT_BORDER_WIDTH = '2px'
const DEFAULT_WIDTH = 600
const DEFAULT_HEIGHT = 400

export {
  DEFAULT_BORDER_COLOR,
  DEFAULT_BORDER_WIDTH,
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT
}
